
### APP
server.port=38080
spring.application.name=opentelemetry-reactive-sample
info.app.name=@project.name@
info.app.description=@project.description@
info.app.version=@project.version@
info.app.encoding=@project.build.sourceEncoding@
info.app.java.version=@java.version@

### OTEL
otel.exporter.otlp.endpoint=http://localhost:4318
otel.exporter.otlp.protocol=http/protobuf
otel.traces.exporter=otlp
otel.metrics.exporter=none

### MANAGEMENT
management.tracing.sampling.probability=1.0
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.metrics.enable.jvm=true
management.metrics.export.prometheus.enabled=true
management.metrics.tags.application=opentelemetry-reactive-sample
management.metrics.distribution.slo.http=5ms,10ms,25ms,50ms,100ms,200ms,300ms,400ms,500ms,1s,2s
management.metrics.distribution.percentiles-histogram.http.server.requests=true


